
import conncetion.ConnectionProvider;
import java.awt.FileDialog;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class StudentRegistration extends javax.swing.JFrame {

    /**
     * Creates new form StudentRegistration
     */
    public StudentRegistration() {
        initComponents();
        //txtGender.setSelectedIndex(-1);
        //txtCourse.setSelectedIndex(-1);
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        String date = dateFormatter.format(now);
        labelDate.setText("DATE: "+date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtRegNumber = new javax.swing.JTextField();
        txtGender = new javax.swing.JComboBox<>();
        photoLabel = new javax.swing.JLabel();
        btnUploadImage = new javax.swing.JButton();
        txtDateOfBirth = new com.toedter.calendar.JDateChooser();
        btnRegister = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtCourse = new javax.swing.JComboBox<>();
        loginLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/index student.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setText("registration form");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 23, -1, -1));

        labelDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDate.setText("Date");
        getContentPane().add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 37, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, 69));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 91, 960, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("NAME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("EMAIL:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("PHONE NUMBER:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 211, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ADDRESS:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("GENDER:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 384, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("REGISTRATION NUMBER:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 328, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("DATE OF BIRTH");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 126, 363, 32));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 169, 363, 29));

        txtPhone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 211, 363, 33));

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 258, 363, 34));

        txtRegNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtRegNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 317, 363, 33));

        txtGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 368, 363, 38));
        getContentPane().add(photoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 244, 213));

        btnUploadImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUploadImage.setText("Upload Image");
        btnUploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadImageActionPerformed(evt);
            }
        });
        getContentPane().add(btnUploadImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, -1, 37));

        txtDateOfBirth.setDateFormatString("dd-MM-yyyy");
        txtDateOfBirth.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 363, 31));

        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 126, 51));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("COURSE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        txtCourse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frontend Web Development", "Backend Web Development", "Full Stack Web Development", "UI/UX Design", "Android/ios Development", "Java Programming", "Graphics Design", "Database Administration", "Networking", "System Analyst", "Desktop Application Development" }));
        getContentPane().add(txtCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 360, 30));

        loginLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(0, 204, 204));
        loginLabel.setText("Already registered? Login Here");
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelMouseClicked(evt);
            }
        });
        getContentPane().add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 380, -1));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 474, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String imagePath = null;
    String admissionStatus = "NOT ADMITTED YET";
    int initialScore = -1;
    
        
    
    public ImageIcon resizeImage(String photopath){
        ImageIcon myImage = new ImageIcon(photopath);
        
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(photoLabel.getWidth(), photoLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
       
    }
    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        new Index().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            int a = JOptionPane.showConfirmDialog(frame, "Do you really want to Exit?","",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnUploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadImageActionPerformed
        // TODO add your handling code here:
        
            
        
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","png","gif");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            photoLabel.setIcon(resizeImage(path));
            this.imagePath = path;
            
            }else if(result == JFileChooser.CANCEL_OPTION){
                System.out.println("No file selected");
            }
        
        
               
        //chooser.setCurrentDirectory(new File(System.getProperty("Pictures")));
        //FileNameExtensionFilter fn = new FileNameExtensionFilter("*images","jpg","png","gif");
        //chooser.addChoosableFileFilter(fn);
        //int returnValue = chooser.showOpenDialog(null);
        
        //int answer = chooser.showSaveDialog(null);
        //if(answer == JFileChooser.APPROVE_OPTION){
         //   File selectedPhoto = chooser.getSelectedFile();
         //  String path = selectedPhoto.getAbsolutePath();
          //  photoLabel.setIcon(resizeImage(path,null));
          // this.photopath = path;
       // }else{
        //    System.out.println("Photo was not selected");
        
        
            
        //}
    }//GEN-LAST:event_btnUploadImageActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        
        String name = txtName.getText();
        String email = txtEmail.getText();
        String regNum = txtRegNumber.getText();
        String address = txtAddress.getText();
        String phone = txtPhone.getText();
        String gender = txtGender.getSelectedItem().toString();
        String course = txtCourse.getSelectedItem().toString();
        Date dob = txtDateOfBirth.getDate();
        
        JFrame frame = new JFrame();
            frame.setAlwaysOnTop(true);
            
        
        if(name.isEmpty()|| name.equals("")){
            JOptionPane.showMessageDialog(frame,"Please Enter your Name" );
            txtName.requestFocus();
        }else if(email.isEmpty()|| email.equals("")){
            JOptionPane.showMessageDialog(frame,"Please Enter your Email" );
            txtEmail.requestFocus();
        }else if(phone.isEmpty()|| phone.equals("")){
            JOptionPane.showMessageDialog(frame,"Please Enter your Phone Number" );
            txtPhone.requestFocus();
            }else if(address.isEmpty()|| address.equals("")){
            JOptionPane.showMessageDialog(frame,"Please Enter your Address" );
            txtAddress.requestFocus();
        }else if(regNum.isEmpty()|| regNum.equals("")){
            JOptionPane.showMessageDialog(frame,"Please Enter your Registration number" );
            txtRegNumber.requestFocus();
        }else if(gender.isEmpty()|| gender.equals("")){
            JOptionPane.showMessageDialog(frame,"Please Select Your Gender" );
        }else if(course.isEmpty()|| course.equals("")){
            JOptionPane.showMessageDialog(frame,"Please Choose a Course" );
        }
        else if(dob==null){
            JOptionPane.showMessageDialog(frame, "Please select date of birth");
            txtDateOfBirth.grabFocus();
        }else{
            JOptionPane.showMessageDialog(frame, "All fields were filled");
            
           try {
            Connection con = ConnectionProvider.getCon();
            String validateRegNumber = "select * from student where reg_number=?";
            PreparedStatement pst = con.prepareStatement(validateRegNumber);
            pst.setString(1, regNum);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(frame, "Registration Number Already Exist");
            }else{
                String saveQuerry = "insert into student (name,email,address,phone,reg_number,gender,course,date_of_birth,photo,admission_status,exam_score)values(?,?,?,?,?,?,?,?,?,?,?)";
                pst = con.prepareStatement(saveQuerry);
                pst.setString(1, name);
                pst.setString(2, email);
                pst.setString(3, address);
                pst.setString(4, phone);
                pst.setString(5, regNum);
                pst.setString(6, gender);
                pst.setString(7, course);
                
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                String dateOfBirth = dateFormat.format(txtDateOfBirth.getDate());
                pst.setString(8, dateOfBirth);
                
                InputStream photoInput = new FileInputStream(new File(imagePath));
                pst.setBlob(9, photoInput);
                pst.setString(10, admissionStatus);
                pst.setInt(11, initialScore);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(frame, "Registration Successful");
                txtName.setText("");
                txtEmail.setText("");
                txtAddress.setText("");
                txtPhone.setText("");
                txtRegNumber.setText("");
                txtGender.setSelectedIndex(-1);
                txtCourse.setSelectedIndex(-1);
                txtDateOfBirth.setDate(null);
                photoLabel.setIcon(resizeImage(""));
                
            }
            } catch (SQLException ex) {
                Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(frame, "Error in "+ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(frame, "Error in "+ex);
            }
        }
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void loginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseClicked
        // TODO add your handling code here
        
        StudentLogin login = new StudentLogin();
        this.hide();
        new StudentLogin().setVisible(true);
    }//GEN-LAST:event_loginLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUploadImage;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JComboBox<String> txtCourse;
    private com.toedter.calendar.JDateChooser txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JComboBox<String> txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRegNumber;
    // End of variables declaration//GEN-END:variables
}
